trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

resources:
  repositories:
    - repository: templates
      type: github
      name: foxundermoon/rust-azure-pipelines
      ref: refs/heads/nightly ## TODO you may want to change it to refs/tags/TAG_NAME.
      endpoint: github_release


steps:
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: "Install rust (*nix)"
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

  # Windows.
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain nightly
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    env:
      RUSTUP_TOOLCHAIN: nightly
    displayName: "Install rust (windows)"
    condition: eq(variables['Agent.OS'], 'Windows_NT')


  # All platforms.
  - script: |
        rustup -V
        rustup component list --installed
        rustc -Vv
        cargo -V
    displayName: Query rust and cargo versions